geocode-glib_2.updateScript: Fix eval
Fixes `maintainers/scripts/update.nix` returning an error when looking for update scripts:

    error: Cannot find attribute ‘geocode-glib’.

Follow up to 8a11a371d9b9cf63d70edbd85fd2344a95da5def.

(cherry picked from commit 4a2e28d5b6007f8beb1695d40763453f86cc71a5)